config/routes.rb
Rails
  .application
  .routes
  .draw do
    resources :events
    resources :expenses, except: :show
    devise_for :users,
               controllers: {
                 sessions: 'users/sessions',
                 registrations: 'users/registrations',
               }
    devise_scope :user do
      get 'sign_in', to: 'users/sessions#new'
      get 'sign_up', to: 'users/registrations#new'
      get 'forgot_password', to: 'users/passwords#new'
      get 'reset_password', to: 'users/passwords#edit'
    end

    root to: 'home#index'

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    validates :name, presence: true
    validates :location, presence: true
    validates :date, presence: true

    belongs_to :hub

    has_many :expenses
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true
  validates :amount, presence: true, numericality: true

  belongs_to :user
  belongs_to :event
end

app/models/hub.rb
class Hub < ApplicationRecord
  validates :city, presence: true
  validates :country, presence: true

  has_many :users
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  belongs_to :hub, optional: true
  has_many :expenses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to @event
    else
      render :new
    end
  end

  def show
    @event = Event.find(params[:id])
    @expenses = @event.expenses
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to @event
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_url
  end

  private

  def event_params
    params.require(:event).permit(:name, :location, :date, :hub_id)
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  def index
    @expenses = Expense.all
  end

  def new
    @expense = Expense.new
  end

  def create
    @expense = Expense.new(expense_params)
    if @expense.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def update
    @expense = Expense.find(params[:id])
    @expense.update(expense_params)
    redirect_to action: 'index'
  end

  def edit
    @expense = Expense.find(params[:id])
  end

  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    redirect_to action: 'index'
  end

  private

  def expense_params
    params
      .require(:expense)
      .permit(:name, :description, :amount, :user_id, :event_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/events/_form.html.erb
<%= form_for(@event, :html => {class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", role: "form"},) do |f| %>
    <div class="mb-8">
      <%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
      <%= f.text_field :name, autofocus: true, placeholder: "Enter Event Name", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-8">
      <%= f.label :location, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
      <%= f.text_field :location, placeholder: "Location Name", class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-8">
      <%= f.label :hub_id, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
      <%= f.number_field :hub_id, placeholder: "Hub ID", class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-8">
      <%= f.label :date, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
      <%= f.date_select :date, class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="flex items-center justify-between">
      <%= f.submit "Create Event", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>
  <% end %>

app/views/events/edit.html.erb
<div class="m-auto w-full max-w-xs mt-4">
  <h2 class="block text-black-700 text-lg font-bold text-center">Edit Event</h2>
  <%= render "form" %>
</div>

app/views/events/index.html.erb
<div class="container my-12 mx-auto px-4 md:px-12">
    <div class="flex">
        <%= link_to 'Create Event',
                  new_event_path,
                  class: 'button',
                  role: 'button' %>
    </div>
    <div class="flex flex-wrap -mx-1 lg:-mx-4">
    <% @events.each do |event| %>
        <div class="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/3">
            <article class="overflow-hidden rounded-lg shadow-lg">
                <%= link_to event do %>
                <img alt="Placeholder" class="block h-auto w-full" src="https://picsum.photos/600/400/?random">
                <header class="flex items-center justify-between leading-tight p-2 md:p-4">
                    <h1 class="text-lg">
                        <a class="no-underline hover:underline text-black" href="#">
                            <%= event.name %>
                        </a>
                    </h1>
                    <p class="text-grey-darker text-sm">
                        <%= event.date %>
                    </p>
                </header>
                <footer class="flex items-center justify-between leading-none p-2 md:p-4">
                        <img alt="Placeholder" class="block rounded-full" src="https://picsum.photos/32/32/?random">
                        <p class="ml-2 text-sm">
                            <%= event.location %>
                        </p>
                </footer>
                <% end %>
            </article>
        </div>
    <% end %>
    </div>
</div>

app/views/events/new.html.erb
<div class="m-auto w-full max-w-xs mt-4">
  <h2 class="block text-black-700 text-lg font-bold text-center">Create Event</h2>
  <%= render "form" %>
</div>

app/views/events/show.html.erb
<div class="flex">
  <div class="my-8 px-1 w-full md:w-1/2 lg:px-4 lg:w-1/3">
    <article class="overflow-hidden rounded-lg shadow-lg">
      <img
        alt="Placeholder"
        class="block h-auto w-full"
        src="https://picsum.photos/600/400/?random"
      />
      <header
        class="flex items-center justify-between leading-tight p-2 md:p-4"
      >
        <h1 class="text-lg">
          <%= @event.name %>
        </h1>
        <p class="text-grey-darker text-sm">
          <%= @event.date %>
        </p>
      </header>
      <footer class="flex items-center justify-between leading-none p-2 md:p-4">
        <img
          alt="Placeholder"
          class="block rounded-full"
          src="https://picsum.photos/32/32/?random"
        />
        <p class="ml-2 text-sm">
          <%= @event.location %>
        </p>
        <%=
          link_to 'Edit', edit_event_path(@event), class: 'button', role: 'button'
        %>
        <%=
          link_to 'Delete',
                  @event,
                  class: 'button',
                  role: 'button',
                  method: :delete,
                  data: {
                    confirm: 'Are you sure?',
                  }
        %>
      </footer>
    </article>
  </div>
  <div class="my-8 px-1 w-full md:w-1/2 lg:px-4 lg:w-2/3">
    <div class="flex pb-5 w-full">
      <%=
        link_to 'Create Expense',
                new_expense_path,
                class:
                  'button bg-blue-500 font-bold text-white px-4 py-3 transition duration-300 ease-in-out hover:bg-blue-600 mr-6',
                role: 'button'
      %>
    </div>
    <%= render "expenses/table" %>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_for(@expense, :html => {class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", role: "form"},) do |f| %>
  <div class="mb-8">
    <%= f.label :name, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
    <%= f.text_field :name, autofocus: true, placeholder: "Enter Expense Name", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-8">
    <%= f.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
    <%= f.text_area :description, autofocus: true, placeholder: "Enter Expense Description", class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-8">
    <%= f.label :user_id, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
    <%= f.collection_select :user_id, User.all, :id, :email, class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-8">
    <%= f.label :event_id, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
    <%= f.collection_select :event_id, Event.all, :id, :name, class: "shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline" %>
  </div>

  <div class="mb-8">
    <%= f.label :amount, class: "block text-gray-700 text-sm font-bold mb-2" %><br />
    <%=
      f.number_field :amount,
                     step: 0.01,
                     placeholder: 'Amount of the expense',
                     class:
                       'shadow appearance-none border border-red-500 rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline'
    %>
  </div>

  <div class="flex items-center justify-between">
    <%= f.submit "Create Expense", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
  </div>
<% end %>

app/views/expenses/_table.html.erb
<div class="w-full lg:w-5/6">
  <div class="bg-white shadow-md rounded my-6">
    <table class="min-w-max w-full table-auto">
      <thead>
        <tr class="bg-gray-200 text-gray-600 uppercase text-sm leading-normal">
          <th class="py-3 px-6 text-left">Expense Name</th>
          <th class="py-3 px-6 text-left">Expense Description</th>
          <th class="py-3 px-6 text-center">Event</th>
          <th class="py-3 px-6 text-center">Amount</th>
          <th class="py-3 px-6 text-center">Expense Creator</th>
          <th class="py-3 px-6 text-center">Actions</th>
        </tr>
      </thead>
      <tbody class="text-gray-600 text-sm font-light">
        <% @expenses.each do |expense| %>
          <tr class="border-b border-gray-200 hover:bg-gray-100">
            <td class="py-3 px-6 text-left whitespace-nowrap">
              <div class="flex items-center">
                <%= expense.name %>
              </div>
            </td>
            <td class="py-3 px-6 text-left">
              <div class="flex items-center">
                <%= expense.description %>
              </div>
            </td>
            <td class="py-3 px-6 text-center">
              <div class="flex items-center justify-center">
                <%= expense.event.name %>
              </div>
            </td>
            <td class="py-3 px-6 text-center">
              <div class="flex items-center justify-center">
                <%= expense.amount %>
              </div>
            </td>
            <td class="py-3 px-6 text-center">
              <div class="flex items-center justify-center">
                <%= expense.user.firstname %> <%= expense.user.lastname %>
              </div>
            </td>
            <td class="py-3 px-6 text-center">
              <div class="flex item-center justify-center">
                <%= link_to edit_expense_path(expense) do %>
                  <div
                    class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z"
                      />
                    </svg>
                  </div>
                <% end %>
                <%= link_to expense, method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <div
                    class="w-4 mr-2 transform hover:text-purple-500 hover:scale-110"
                  >
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        stroke-width="2"
                        d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
                      />
                    </svg>
                  </div>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
      <tfoot>
        <tr class="border-b border-gray-200 hover:bg-gray-100">
          <td class="py-3 px-6 text-left whitespace-nowrap"></td>
          <td class="py-3 px-6 text-left"></td>
          <td class="py-3 px-6 text-center"></td>
          <td class="py-3 px-6 text-center">
            <div class="flex items-center justify-center">
              <%= @expenses.sum(:amount) %>
            </div>
          </td>
          <td class="py-3 px-6 text-center"></td>
          <td class="py-3 px-6 text-center"></td>
        </tr>
      </tfoot>
    </table>
  </div>
</div>

app/views/expenses/edit.html.erb
<div class="m-auto w-full max-w-xs mt-4">
  <h2 class="block text-black-700 text-lg font-bold text-center">
    Edit Expense
  </h2>
  <%= render "form" %>
</div>

app/views/expenses/index.html.erb
<div class="overflow-x-auto">
  <div class="flex p-10 bg-gray-100 w-full">
    <%=
      link_to 'Create Expense',
              new_expense_path,
              class:
                'button bg-blue-500 font-bold text-white px-4 py-3 transition duration-300 ease-in-out hover:bg-blue-600 mr-6',
              role: 'button'
    %>
  </div>
  <div
    class="min-w-screen bg-gray-100 flex items-center justify-center bg-gray-100 font-sans overflow-hidden"
  >
    <%= render "table" %>
  </div>
</div>

app/views/expenses/new.html.erb
<div class="m-auto w-full max-w-xs mt-4">
  <h2 class="block text-black-700 text-lg font-bold text-center">
    Create Expense
  </h2>
  <%= render "form" %>
</div>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lovebook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
	  <link rel="stylesheet" href="https://rsms.me/inter/inter.css">

	  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>